version: '3.8'

services:
  app:
    build:
      context: .  # 현재 디렉터리를 Docker 빌드 컨텍스트로 설정
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
