spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: localhost
    port: 6379

#logging:
#  level:
#    org:
#      springframework: WARN

#  ai:
#    openai:
#      api-key: ${spring.ai.openai.api-key}
#      model: gpt-4o-mini
#      api:
#        url: https://api.openai.com/v1/chat/completions
#  data:
#    redis:
#      host: redis
#      port: 6379
#    mongodb:
#      uri: mongodb://mongodb:27017/morakg
#      database: morak
#
